# taken from gufe to match the style there
ci:
  autoupdate_schedule: "quarterly"
  # comment / label "pre-commit.ci autofix" to a pull request to manually trigger auto-fixing
  autofix_prs: false
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-symlinks
  - id: check-toml
  - id: check-yaml
  - id: debug-statements
  - id: destroyed-symlinks
  - id: end-of-file-fixer
    exclude: '\.(graphml)$'
  - id: trailing-whitespace
    exclude: '\.(pdb|gro|top|sdf|xml|cif|graphml)$'

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.12
  hooks:
    # Run the linter.
    - id: ruff
      args: [--fix ]
    # Run the formatter.
    - id: ruff-format

- repo: https://github.com/econchick/interrogate
  rev: 1.7.0
  hooks:
    - id: interrogate
      args: [--fail-under=28]
      pass_filenames: false