name: cinnabar
channels:
- conda-forge
dependencies:
- python
- pip
- numpy
- networkx
- scikit-learn
- adjustText
- openff-units
- sphinx
- sphinx_rtd_theme
- pip:
  - sphinx-design
  - sphinx-toolbox
